import http from "node:http";
const pages = await new Promise((resolve, reject) => http.get("http://127.0.0.1:9222/json/list", response => { let data = ""; response.on("data", chunk => data += chunk); response.on("end", () => resolve(JSON.parse(data))); }).on("error", reject));
const target = pages.find(page => page.type === "page" && page.url.includes("/payroll"));
if (!target) throw new Error("Nuk u gjet tab-i i Pagave.");
const ws = new WebSocket(target.webSocketDebuggerUrl);
let id = 0;
const pending = new Map();
ws.addEventListener("message", event => { const message = JSON.parse(String(event.data)); if (message.id && pending.has(message.id)) { pending.get(message.id)(message); pending.delete(message.id); } });
await new Promise((resolve, reject) => { ws.addEventListener("open", resolve, { once: true }); ws.addEventListener("error", reject, { once: true }); });
const command = (method, params = {}) => new Promise((resolve, reject) => { const callId = ++id; pending.set(callId, response => response.error ? reject(new Error(JSON.stringify(response.error))) : resolve(response.result)); ws.send(JSON.stringify({ id: callId, method, params })); });
const evaluate = async expression => (await command("Runtime.evaluate", { expression, returnByValue: true, awaitPromise: true })).result?.value;
await command("Page.bringToFront");
await new Promise(resolve => setTimeout(resolve, 700));
const root = await command("DOM.getDocument", { depth: -1 });
const input = await command("DOM.querySelector", { nodeId: root.root.nodeId, selector: "input[type=file]" });
if (!input.nodeId) throw new Error("Nuk u gjet input-i i importit manual.");
await command("DOM.setFileInputFiles", { nodeId: input.nodeId, files: ["/home/ubuntu/upload/07.PAGATMUAJIKORRIK2026.xlsx"] });
await new Promise(resolve => setTimeout(resolve, 1800));
const text = await evaluate("document.body.innerText");
console.log(JSON.stringify({url: target.url, uploaded: text.includes('07.PAGATMUAJIKORRIK2026.xlsx'), preview: text.slice(0, 6000)}, null, 2));
ws.close();
