import http from "node:http";
const target = await new Promise((resolve, reject) => http.get("http://127.0.0.1:9222/json/list", response => { let data = ""; response.on("data", chunk => data += chunk); response.on("end", () => resolve(JSON.parse(data).find(page => page.type === "page" && page.url.includes("/payroll")))); }).on("error", reject));
const ws = new WebSocket(target.webSocketDebuggerUrl);
let id = 0;
const pending = new Map();
ws.addEventListener("message", event => { const message = JSON.parse(String(event.data)); if (message.id && pending.has(message.id)) { pending.get(message.id)(message); pending.delete(message.id); } });
await new Promise((resolve, reject) => { ws.addEventListener("open", resolve, { once: true }); ws.addEventListener("error", reject, { once: true }); });
const command = (method, params = {}) => new Promise((resolve, reject) => { const callId = ++id; pending.set(callId, response => response.error ? reject(new Error(JSON.stringify(response.error))) : resolve(response.result)); ws.send(JSON.stringify({ id: callId, method, params })); });
const evaluate = async expression => (await command("Runtime.evaluate", { expression, returnByValue: true, awaitPromise: true })).result?.value;
await command("Page.bringToFront");
await command("DOM.enable");
await new Promise(resolve => setTimeout(resolve, 800));
const root = await command("DOM.getDocument", { depth: -1 });
const input = await command("DOM.querySelector", { nodeId: root.root.nodeId, selector: "input[type=file]" });
if (!input.nodeId) throw new Error("Nuk u gjet input-i i log-ut.");
await command("DOM.setFileInputFiles", { nodeId: input.nodeId, files: ["/home/ubuntu/upload/001_2026_8_MON.XLS"] });
await new Promise(resolve => setTimeout(resolve, 2200));
const clicked = await evaluate(`(() => { const button = [...document.querySelectorAll('button')].find(item => item.textContent?.trim() === 'Shkarko pa gisht'); if (!button) return false; button.click(); return true; })()`);
await new Promise(resolve => setTimeout(resolve, 900));
const result = await evaluate(`({clicked: ${JSON.stringify(clicked)}, text: document.body.innerText.slice(0, 5000), url: location.href})`);
console.log(JSON.stringify(result, null, 2));
ws.close();
