import { useMemo, useState } from "react";
import { Download, FileText, History, Printer, Search, Trash2, XCircle } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { trpc } from "@/lib/trpc";
import { exportToExcel, exportToPDF } from "@/lib/export";

const actionLabel: Record<string, string> = { CREATE: "Krijuar", UPDATE: "Modifikuar", CANCEL: "Anuluar", DELETE: "Fshirë", PAY: "Paguar", POST: "Postuar", SEND: "Dërguar", UPLOAD: "Skedar i ngarkuar", GENERATE: "Gjeneruar" };
const entityLabel: Record<string, string> = { PURCHASE_INVOICE: "Faturë blerjeje", SALES_INVOICE: "Faturë shitjeje", PURCHASE_ORDER: "Porosi blerjeje", SALES_ORDER: "Porosi shitjeje", PAYMENT: "Pagesë", BANK_TRANSFER: "Transfer bankar", CREDIT_NOTE: "Nota Krediti", USER_COMPANY_ROLE: "Roli i përdoruesit", PAYROLL_PERIOD: "Periudha e pagave" };
type ActionExportRow = { Data: string; Veprimi: string; Dokumenti: string; ID: string; Përdoruesi: string; Detaje: string };
const columns: Array<{ key: keyof ActionExportRow; label: string }> = [{ key: "Data", label: "Data" }, { key: "Veprimi", label: "Veprimi" }, { key: "Dokumenti", label: "Dokumenti" }, { key: "ID", label: "ID" }, { key: "Përdoruesi", label: "Përdoruesi" }, { key: "Detaje", label: "Detaje" }];
const escapeHtml = (value: string) => value.replace(/[&<>"']/g, char => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#039;" })[char] || char);

export default function Actions({ companyId, title = "Veprimet" }: { companyId: number; title?: string }) {
  const { data: entries = [], isLoading } = trpc.auditLog.list.useQuery({ companyId });
  const [search, setSearch] = useState("");
  const [filter, setFilter] = useState("ALL");
  const visible = useMemo(() => { const term = search.trim().toLocaleLowerCase("sq-AL"); return entries.filter(entry => (filter === "ALL" || entry.action === filter) && (!term || [entry.details, entry.entityType, entry.userName, entry.action, entry.entityId?.toString()].some(value => value?.toLocaleLowerCase("sq-AL").includes(term)))); }, [entries, search, filter]);
  const rows = useMemo<ActionExportRow[]>(() => visible.map(entry => ({ Data: entry.createdAt ? new Date(entry.createdAt).toLocaleString("sq-AL") : "—", Veprimi: actionLabel[entry.action || ""] || entry.action || "Veprim", Dokumenti: entityLabel[entry.entityType || ""] || entry.entityType || "—", ID: String(entry.entityId ?? "—"), Përdoruesi: entry.userName || "Përdorues i sistemit", Detaje: entry.details || "—" })), [visible]);
  const actions = ["ALL", "CREATE", "UPDATE", "PAY", "POST", "CANCEL", "DELETE", "GENERATE"];
  const exportExcel = () => exportToExcel(rows, title.replaceAll(" ", "-"), title, columns);
  const exportPdf = () => exportToPDF(rows, title.replaceAll(" ", "-"), title, columns);
  const printPreview = () => { const popup = window.open("", "_blank", "width=1200,height=800"); if (!popup) return; const header = columns.map(column => `<th>${escapeHtml(column.label)}</th>`).join(""); const body = rows.map(row => `<tr>${columns.map(column => `<td>${escapeHtml(row[column.key])}</td>`).join("")}</tr>`).join(""); popup.document.write(`<!doctype html><html lang="sq"><head><title>${escapeHtml(title)}</title><style>body{font-family:Arial,sans-serif;color:#332d33;padding:28px}h1{color:#714b67;font-size:22px;margin:0 0 6px}p{color:#625c62;font-size:12px;margin:0 0 18px}table{width:100%;border-collapse:collapse;font-size:12px}th{background:#714b67;color:#fff;text-align:left;padding:9px}td{border:1px solid #ded8df;padding:8px;vertical-align:top}@media print{body{padding:0}}</style></head><body><h1>${escapeHtml(title)}</h1><p>${rows.length} rreshta · Filtri: ${escapeHtml(filter === "ALL" ? "Të gjitha" : actionLabel[filter] || filter)}${search ? ` · Kërkimi: ${escapeHtml(search)}` : ""}</p><table><thead><tr>${header}</tr></thead><tbody>${body || `<tr><td colspan="${columns.length}">Nuk ka veprime që përputhen.</td></tr>`}</tbody></table><script>window.onload=()=>window.print()</script></body></html>`); popup.document.close(); };
  return <section className="space-y-4"><header className="flex flex-col gap-3 border-b border-[#ded8df] pb-4 md:flex-row md:items-center md:justify-between"><h1 className="text-xl font-semibold text-[#332d33]">{title}</h1><div className="flex flex-wrap items-center gap-2"><Button size="sm" variant="outline" disabled={!rows.length} onClick={exportExcel}><Download className="mr-1.5 h-4 w-4" />Excel</Button><Button size="sm" variant="outline" disabled={!rows.length} onClick={exportPdf}><FileText className="mr-1.5 h-4 w-4" />PDF</Button><Button size="sm" variant="outline" disabled={!rows.length} onClick={printPreview}><Printer className="mr-1.5 h-4 w-4" />Print Preview</Button><div className="relative min-w-[280px]"><Search className="absolute left-3 top-2.5 h-4 w-4 text-[#777]" /><Input value={search} onChange={event => setSearch(event.target.value)} className="h-9 bg-white pl-9" placeholder="Kërko dokument, përdorues ose veprim…" /></div></div></header><div className="flex flex-wrap gap-1 border-b border-[#ded8df] pb-3">{actions.map(action => <button type="button" key={action} onClick={() => setFilter(action)} className={`rounded px-3 py-1.5 text-xs font-semibold ${filter === action ? "bg-[#714b67] text-white" : "bg-white text-[#625c62] hover:bg-[#f6eef5]"}`}>{action === "ALL" ? "Të gjitha" : actionLabel[action] || action}</button>)}</div><div className="overflow-x-auto rounded-md border border-[#ded8df] bg-white"><table className="w-full min-w-[900px] text-sm"><thead className="bg-[#f8f7f8] text-left text-xs font-semibold uppercase tracking-wide text-[#625c62]"><tr>{columns.map(column => <th key={column.key} className="px-4 py-3">{column.label}</th>)}</tr></thead><tbody>{isLoading ? <tr><td colSpan={columns.length} className="p-10 text-center text-[#777]">Po ngarkohen veprimet…</td></tr> : rows.length === 0 ? <tr><td colSpan={columns.length} className="p-10 text-center text-[#777]"><History className="mx-auto mb-2 h-5 w-5" />Nuk ka veprime që përputhen.</td></tr> : visible.map((entry, index) => <tr className="border-t border-[#eee9ee]" key={entry.id}><td className="whitespace-nowrap px-4 py-3">{rows[index]?.Data}</td><td className="px-4 py-3"><span className={`inline-flex items-center gap-1 rounded px-2 py-1 text-xs font-semibold ${entry.action === "DELETE" ? "bg-red-100 text-red-700" : entry.action === "CANCEL" ? "bg-amber-100 text-amber-800" : "bg-[#f2eaf1] text-[#714b67]"}`}>{entry.action === "DELETE" ? <Trash2 className="h-3.5 w-3.5" /> : entry.action === "CANCEL" ? <XCircle className="h-3.5 w-3.5" /> : null}{rows[index]?.Veprimi}</span></td><td className="px-4 py-3">{rows[index]?.Dokumenti}</td><td className="px-4 py-3">{rows[index]?.ID}</td><td className="px-4 py-3">{rows[index]?.Përdoruesi}</td><td className="px-4 py-3">{rows[index]?.Detaje}</td></tr>)}</tbody></table></div></section>;
}
