import { useMemo, useState } from "react";
import { useLocation } from "wouter";
import { FilePenLine, FilePlus2, Printer, RefreshCw, Ruler, Search, Trash2, XCircle } from "lucide-react";
import { toast } from "sonner";
import { trpc } from "@/lib/trpc";
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";

type Mode = "create" | "edit" | null;

export default function MeasurementUnits({ companyId }: { companyId: number }) {
  const [, navigate] = useLocation();
  const utils = trpc.useUtils();
  const unitsQuery = trpc.unit.list.useQuery({ companyId });
  const [draftSearch, setDraftSearch] = useState("");
  const [search, setSearch] = useState("");
  const [selectedId, setSelectedId] = useState<number | null>(null);
  const [mode, setMode] = useState<Mode>(null);
  const units = unitsQuery.data ?? [];
  const rows = useMemo(() => { const term = search.trim().toLocaleLowerCase("sq-AL"); return units.filter(unit => !term || `${unit.name} ${unit.abbreviation || ""}`.toLocaleLowerCase("sq-AL").includes(term)); }, [units, search]);
  const selected = rows.find(unit => unit.id === selectedId) ?? units.find(unit => unit.id === selectedId);
  const refresh = async () => { await utils.unit.list.invalidate({ companyId }); await unitsQuery.refetch(); toast.success("Lista u rifreskua."); };
  const create = trpc.unit.create.useMutation({ onSuccess: async () => { await refresh(); setMode(null); toast.success("Njësia e matjes u ruajt."); }, onError: error => toast.error(error.message) });
  const update = trpc.unit.update.useMutation({ onSuccess: async () => { await refresh(); setMode(null); toast.success("Njësia e matjes u përditësua."); }, onError: error => toast.error(error.message) });
  const remove = trpc.unit.delete.useMutation({ onSuccess: async () => { setSelectedId(null); await refresh(); toast.success("Njësia e matjes u fshi."); }, onError: error => toast.error(error.message) });
  const printList = () => { const popup = window.open("", "_blank", "width=800,height=600"); if (!popup) return toast.error("Print Preview u bllokua nga shfletuesi."); popup.document.write(`<!doctype html><html><head><title>Njësi Matje</title><style>body{font:12px Tahoma,Arial;padding:20px}table{width:100%;border-collapse:collapse}th,td{border:1px solid #9aa;padding:6px;text-align:left}th{background:#d6e1e8}</style></head><body><h1>Njësi Matje</h1><table><thead><tr><th>Nr.</th><th>Kodi</th><th>Përshkrimi</th></tr></thead><tbody>${rows.map((unit,index) => `<tr><td>${index+1}</td><td>${unit.abbreviation || ""}</td><td>${unit.name}</td></tr>`).join("")}</tbody></table><script>window.onload=()=>window.print()</script></body></html>`); popup.document.close(); };
  const askDelete = () => { if (!selected) return toast.error("Zgjidhni një njësi nga grila."); if (window.confirm(`Fshi njësinë e matjes “${selected.name}”? Artikujt që e përdorin e bllokojnë fshirjen.`)) remove.mutate({ companyId, id: selected.id }); };
  return <section className="alpha-liquidity-canvas" aria-label="Njësi Matje"><div className="alpha-liquidity-window"><div className="alpha-liquidity-titlebar"><div className="flex items-center gap-1.5"><Ruler className="h-4 w-4 text-[#496f8c]" /><h1>Njësi Matje</h1></div><button type="button" onClick={() => navigate("/")} className="alpha-liquidity-close">×</button></div><div className="alpha-liquidity-toolbar print:hidden"><MeasureTool icon={<FilePlus2 />} label="Shto" onClick={() => setMode("create")} /><MeasureTool icon={<FilePenLine />} label="Modifiko" disabled={!selected} onClick={() => selected ? setMode("edit") : undefined} /><MeasureTool icon={<Trash2 />} label="Fshi" disabled={!selected || remove.isPending} onClick={askDelete} danger /><MeasureTool icon={<RefreshCw />} label="Rifresko" onClick={() => void refresh()} /><MeasureTool icon={<Printer />} label="Printo" onClick={printList} /><span className="mx-1 h-9 w-px bg-[#abb8c0]" /><MeasureTool icon={<XCircle />} label="Mbyll" onClick={() => navigate("/")} danger /></div><form className="alpha-liquidity-search print:hidden" onSubmit={event => { event.preventDefault(); setSearch(draftSearch); }}><label>Kërko:<Input value={draftSearch} onChange={event => setDraftSearch(event.target.value)} placeholder="Kodi ose përshkrimi" className="h-6 rounded-none border-[#8d9da8] bg-white px-1.5 text-[11px]" /></label><button type="submit"><Search className="h-3.5 w-3.5" />Kërko</button></form><div className="alpha-liquidity-grid-wrap"><table className="alpha-liquidity-grid"><thead><tr><th className="w-[55px]">Nr.</th><th className="w-[160px]">Kodi</th><th>Përshkrimi</th></tr></thead><tbody>{unitsQuery.isLoading ? <tr><td colSpan={3} className="alpha-liquidity-empty">Po ngarkohet lista…</td></tr> : rows.length ? rows.map((unit,index) => <tr key={unit.id} onClick={() => setSelectedId(unit.id)} onDoubleClick={() => setMode("edit")} className={selectedId === unit.id ? "is-selected" : ""}><td>{index+1}</td><td>{unit.abbreviation || "—"}</td><td>{unit.name}</td></tr>) : <tr><td colSpan={3} className="alpha-liquidity-empty">Nuk ka njësi matjeje të regjistruara.</td></tr>}</tbody></table></div><footer className="alpha-liquidity-statusbar">{rows.length} njësi · Përdoret te Artikujt për Kg, Copë, Litër dhe njësi të tjera.</footer></div><MeasureEditor open={mode !== null} mode={mode} initial={selected} pending={create.isPending || update.isPending} onOpenChange={open => !open && setMode(null)} onSave={data => mode === "edit" && selected ? update.mutate({ companyId, id: selected.id, ...data }) : create.mutate({ companyId, ...data })} /></section>;
}

function MeasureTool({ icon, label, onClick, disabled = false, danger = false }: { icon: React.ReactNode; label: string; onClick: () => void; disabled?: boolean; danger?: boolean }) { return <button type="button" onClick={onClick} disabled={disabled} className={`alpha-liquidity-toolbar-button ${danger ? "is-danger" : ""}`}><span>{icon}</span><small>{label}</small></button>; }

function MeasureEditor({ open, mode, initial, pending, onOpenChange, onSave }: { open: boolean; mode: Mode; initial?: { name: string; abbreviation: string | null }; pending: boolean; onOpenChange: (open: boolean) => void; onSave: (data: { name: string; abbreviation?: string }) => void }) { const editing = mode === "edit"; return <Dialog open={open} onOpenChange={onOpenChange}><DialogContent className="alpha-liquidity-editor p-0"><DialogHeader className="alpha-liquidity-titlebar"><DialogTitle>{editing ? "Modifiko Njësinë e Matjes" : "Çelja e Njësisë së Matjes"}</DialogTitle><DialogDescription className="sr-only">Përkufizoni njësinë që përdoret te artikujt.</DialogDescription></DialogHeader><form className="space-y-3 p-4" onSubmit={event => { event.preventDefault(); const form = new FormData(event.currentTarget); const name = String(form.get("name") || "").trim(); if (!name) return toast.error("Përshkrimi është i detyrueshëm."); onSave({ name, abbreviation: String(form.get("abbreviation") || "").trim() || undefined }); }}><fieldset className="alpha-liquidity-fieldset"><legend>Të dhënat e njësisë</legend><div className="grid gap-3 sm:grid-cols-2"><label className="alpha-liquidity-label">Kodi<Input name="abbreviation" maxLength={10} defaultValue={initial?.abbreviation || ""} className="h-7 rounded-none border-[#8d9da8] px-1.5" placeholder="Kg" /></label><label className="alpha-liquidity-label">Përshkrimi<Input name="name" required maxLength={50} defaultValue={initial?.name || ""} className="h-7 rounded-none border-[#8d9da8] px-1.5" placeholder="Kilogram" /></label></div></fieldset><p className="text-[11px] text-[#596f7f]">P.sh. kodi Kg me përshkrimin Kilogram ose kodi copë me përshkrimin Copë. Njësia përdoret te artikujt.</p><div className="flex justify-end gap-2 border-t border-[#b9c5cc] pt-3"><button type="button" onClick={() => onOpenChange(false)} className="alpha-liquidity-action">Anullo</button><button type="submit" disabled={pending} className="alpha-liquidity-save">{pending ? "Po ruhet…" : "Ruaj"}</button></div></form></DialogContent></Dialog>; }
