import { useMemo, useState } from "react";
import { useLocation } from "wouter";
import { FilePlus2, FileSpreadsheet, LogOut, Pencil, Printer, Search, Trash2, X } from "lucide-react";
import { trpc } from "@/lib/trpc";
import { exportToExcel } from "@/lib/export";
import AlphaCatalogWindow from "@/components/AlphaCatalogWindow";
import { Dialog, DialogContent, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { Button } from "@/components/ui/button";

type CatalogType = "cities" | "partnerCategories" | "dueDates" | "discountCategories" | "issuers" | "document-groups" | "cost-centers";
const titles: Record<CatalogType, string> = { cities: "Qytete", partnerCategories: "Kategori Klienti/Furnitori", dueDates: "Afate Maturimi", discountCategories: "Kategori Zbritje", issuers: "Emetuesit", "document-groups": "Grupim Dokumentash", "cost-centers": "Qendrat e Kostos" };
type CatalogRow = { id?: number; code: string; name: string; type?: string; active?: string; mainProduction?: string };

export default function ReferenceCatalog({ companyId }: { companyId: number }) {
  const [location, navigate] = useLocation();
  const type = (new URLSearchParams(typeof window !== "undefined" ? window.location.search : location.split("?")[1] ?? "").get("type") ?? "cities") as CatalogType;
  const title = titles[type] ?? titles.cities;
  const [search, setSearch] = useState("");
  const [editorOpen, setEditorOpen] = useState(false);
  const [editorId, setEditorId] = useState<number | null>(null);
  const [form, setForm] = useState({ code: "", name: "", documentType: "INVOICE", active: true, mainProduction: false });
  const customers = trpc.customer.list.useQuery({ companyId });
  const suppliers = trpc.supplier.list.useQuery({ companyId });
  const issuers = trpc.issuer.list.useQuery({ companyId }, { enabled: type === "issuers" });
  const documentGroups = trpc.documentGroup.list.useQuery({ companyId }, { enabled: type === "document-groups" });
  const costCenters = trpc.costCenter.list.useQuery({ companyId }, { enabled: type === "cost-centers" });
  const createIssuer = trpc.issuer.create.useMutation({ onSuccess: () => { void issuers.refetch(); setEditorOpen(false); setForm({ code: "", name: "", documentType: "INVOICE", active: true, mainProduction: false }); } });
  const createDocumentGroup = trpc.documentGroup.create.useMutation({ onSuccess: () => { void documentGroups.refetch(); setEditorOpen(false); setForm({ code: "", name: "", documentType: "INVOICE", active: true, mainProduction: false }); } });
  const createCostCenter = trpc.costCenter.create.useMutation({ onSuccess: () => { void costCenters.refetch(); setEditorOpen(false); setEditorId(null); setForm({ code: "", name: "", documentType: "INVOICE", active: true, mainProduction: false }); } });
  const updateIssuer = trpc.issuer.update.useMutation({ onSuccess: () => { void issuers.refetch(); setEditorOpen(false); setEditorId(null); } });
  const updateDocumentGroup = trpc.documentGroup.update.useMutation({ onSuccess: () => { void documentGroups.refetch(); setEditorOpen(false); setEditorId(null); } });
  const updateCostCenter = trpc.costCenter.update.useMutation({ onSuccess: () => { void costCenters.refetch(); setEditorOpen(false); setEditorId(null); } });
  const deleteIssuer = trpc.issuer.delete.useMutation({ onSuccess: () => void issuers.refetch() });
  const deleteDocumentGroup = trpc.documentGroup.delete.useMutation({ onSuccess: () => void documentGroups.refetch() });
  const deleteCostCenter = trpc.costCenter.delete.useMutation({ onSuccess: () => void costCenters.refetch() });
  const rows = useMemo<CatalogRow[]>(() => {
    if (type === "issuers") return (issuers.data ?? []).map(row => ({ id: row.id, code: row.code, name: row.name, active: Number(row.active) === 1 ? "Po" : "Jo" }));
    if (type === "document-groups") return (documentGroups.data ?? []).map(row => ({ id: row.id, code: row.code, name: row.name, type: row.documentType }));
    if (type === "cost-centers") return (costCenters.data ?? []).map(row => ({ id: row.id, code: row.code, name: row.name, active: Number(row.active) === 1 ? "Po" : "Jo", mainProduction: Number(row.mainProduction) === 1 ? "Po" : "Jo" }));
    const values = type === "cities" ? [...(customers.data ?? []).map(row => row.city), ...(suppliers.data ?? []).map(row => row.city)] : [];
    return Array.from(new Set(values.map(value => String(value ?? "").trim()).filter(Boolean))).sort((a, b) => a.localeCompare(b, "sq-AL")).map(value => ({ code: "", name: value }));
  }, [costCenters.data, customers.data, documentGroups.data, issuers.data, suppliers.data, type]);
  const visible = rows.filter(row => { const needle = search.trim().toLocaleLowerCase("sq-AL"); return !needle || [row.code, row.name, row.type, row.active, row.mainProduction].some(value => String(value ?? "").toLocaleLowerCase("sq-AL").includes(needle)); });
  const print = () => window.print();
  const exportRows = () => exportToExcel(visible.map((row, index) => ({ Nr: index + 1, Kodi: row.code, Përshkrimi: row.name, Lloji: row.type ?? "", Aktiv: row.active ?? "", QendraKryesoreProdhimi: row.mainProduction ?? "" })), title.replaceAll(" ", "_"), title);
  const canCreate = type === "issuers" || type === "document-groups" || type === "cost-centers";
  const openNew = () => { setEditorId(null); setForm({ code: "", name: "", documentType: "INVOICE", active: true, mainProduction: false }); setEditorOpen(true); };
  const openEdit = (row: CatalogRow) => { if (!row.id) return; setEditorId(row.id); setForm({ code: row.code, name: row.name, documentType: row.type || "INVOICE", active: row.active !== "Jo", mainProduction: row.mainProduction === "Po" }); setEditorOpen(true); };
  const deleteRow = (row: CatalogRow) => { if (!row.id || !window.confirm(`Fshi ${row.name}?`)) return; if (type === "issuers") deleteIssuer.mutate({ companyId, id: row.id }); else if (type === "document-groups") deleteDocumentGroup.mutate({ companyId, id: row.id }); else if (type === "cost-centers") deleteCostCenter.mutate({ companyId, id: row.id }); };
  const submit = (event: React.FormEvent) => { event.preventDefault(); if (!form.code.trim() || !form.name.trim()) return; if (type === "issuers") { if (editorId) updateIssuer.mutate({ companyId, id: editorId, code: form.code.trim(), name: form.name.trim(), active: form.active ? 1 : 0 }); else createIssuer.mutate({ companyId, code: form.code.trim(), name: form.name.trim(), active: form.active ? 1 : 0 }); } else if (type === "cost-centers") { if (editorId) updateCostCenter.mutate({ companyId, id: editorId, code: form.code.trim(), name: form.name.trim(), active: form.active ? 1 : 0, mainProduction: form.mainProduction ? 1 : 0 }); else createCostCenter.mutate({ companyId, code: form.code.trim(), name: form.name.trim(), active: form.active ? 1 : 0, mainProduction: form.mainProduction ? 1 : 0 }); } else if (editorId) updateDocumentGroup.mutate({ companyId, id: editorId, code: form.code.trim(), name: form.name.trim(), documentType: form.documentType }); else createDocumentGroup.mutate({ companyId, code: form.code.trim(), name: form.name.trim(), documentType: form.documentType }); };
  return <AlphaCatalogWindow title={`Lista e ${title}`} subtitle="Katalog referencë — kompania aktive" count={visible.length} onClose={() => navigate("/")} onRefresh={() => void Promise.all([customers.refetch(), suppliers.refetch(), issuers.refetch(), documentGroups.refetch(), costCenters.refetch()])} onPrint={print} onExport={exportRows} onNew={canCreate ? openNew : undefined}>
    <div className="flex items-end gap-2 border-b border-[#becbd4] bg-white p-2"><label className="text-[11px] font-semibold text-[#3d5568]">Kërko në të gjitha fushat<input value={search} onChange={event => setSearch(event.target.value)} className="mt-0.5 h-7 w-72 border border-[#9fadb7] px-2 text-xs outline-none focus:border-[#2b78b5]" placeholder={`Kërko ${title.toLocaleLowerCase("sq-AL")}...`} /></label><span className="pb-1 text-[11px] text-[#667887]"><Search className="mr-1 inline h-3.5 w-3.5" />{visible.length} rezultate</span></div>
    <div className="overflow-x-auto bg-white p-2"><table className="w-full min-w-[680px] border-collapse text-xs"><thead><tr className="bg-gradient-to-b from-[#e8f0f5] to-[#ccdbe5] text-left text-[#264c66]"><th className="w-16 border border-[#aebdc7] px-2 py-1 font-bold">Nr.</th><th className="border border-[#aebdc7] px-2 py-1 font-bold">Kodi</th>{type === "issuers" ? <th className="border border-[#aebdc7] px-2 py-1 font-bold">Emetuesi</th> : <th className="border border-[#aebdc7] px-2 py-1 font-bold">Emërtimi</th>}{type === "document-groups" && <th className="border border-[#aebdc7] px-2 py-1 font-bold">Lloji</th>}{type === "cost-centers" && <><th className="border border-[#aebdc7] px-2 py-1 font-bold">Qendra kryesore e prodhimit</th><th className="border border-[#aebdc7] px-2 py-1 font-bold">Aktive</th></>}{type !== "issuers" && type !== "cost-centers" && type !== "document-groups" && <th className="border border-[#aebdc7] px-2 py-1 font-bold">Gjendja</th>}<th className="border border-[#aebdc7] px-2 py-1 font-bold">Veprime</th></tr></thead><tbody>{visible.length === 0 ? <tr><td colSpan={type === "cost-centers" ? 6 : type === "issuers" ? 4 : 5} className="border border-[#c2cbd2] p-6 text-center text-[#687986]">Nuk u gjet asnjë regjistrim.</td></tr> : visible.map((row, index) => <tr key={`${row.code}-${row.name}`} className="hover:bg-[#eaf4fa]"><td className="border border-[#c2cbd2] px-2 py-1">{index + 1}</td><td className="border border-[#c2cbd2] px-2 py-1">{row.code || "—"}</td><td className="border border-[#c2cbd2] px-2 py-1 font-medium">{row.name}</td>{type === "document-groups" && <td className="border border-[#c2cbd2] px-2 py-1">{row.type || "—"}</td>}{type === "cost-centers" && <><td className="border border-[#c2cbd2] px-2 py-1">{row.mainProduction || "Jo"}</td><td className="border border-[#c2cbd2] px-2 py-1">{row.active || "—"}</td></>}{type !== "issuers" && type !== "cost-centers" && type !== "document-groups" && <td className="border border-[#c2cbd2] px-2 py-1">—</td>}<td className="border border-[#c2cbd2] px-2 py-1"><div className="flex gap-1"><button type="button" onClick={() => openEdit(row)} disabled={!row.id} className="border border-[#b3c1cb] p-1 text-[#2b6892] hover:bg-[#eaf4fa] disabled:opacity-40" aria-label={`Ndrysho ${row.name}`}><Pencil className="h-3.5 w-3.5" /></button><button type="button" onClick={() => deleteRow(row)} disabled={!row.id} className="border border-[#d0b0b0] p-1 text-[#9b3a3a] hover:bg-[#fff0f0] disabled:opacity-40" aria-label={`Fshi ${row.name}`}><Trash2 className="h-3.5 w-3.5" /></button></div></td></tr>)}</tbody></table></div>
    <Dialog open={editorOpen} onOpenChange={setEditorOpen}><DialogContent className="max-w-md rounded-sm border-[#8199aa] p-0"><DialogHeader className="border-b border-[#92a8b7] bg-gradient-to-b from-[#eaf3f8] to-[#c9dbe6] px-3 py-2"><DialogTitle className="text-[13px] text-[#234b67]">{editorId ? "Ndrysho" : type === "issuers" ? "Emetues i Ri" : type === "cost-centers" ? "Qendër Kostoje e Re" : "Grup Dokumentash i Ri"}</DialogTitle></DialogHeader><form onSubmit={submit} className="space-y-3 p-4"><label className="block text-xs font-semibold text-[#3d5568]">Kodi<Input value={form.code} onChange={event => setForm(current => ({ ...current, code: event.target.value }))} className="mt-1 h-8 rounded-none border-[#9fadb7]" required /></label><label className="block text-xs font-semibold text-[#3d5568]">Emërtimi<Input value={form.name} onChange={event => setForm(current => ({ ...current, name: event.target.value }))} className="mt-1 h-8 rounded-none border-[#9fadb7]" required /></label>{type === "document-groups" ? <label className="block text-xs font-semibold text-[#3d5568]">Lloji<select value={form.documentType} onChange={event => setForm(current => ({ ...current, documentType: event.target.value }))} className="mt-1 h-8 w-full border border-[#9fadb7] bg-white px-2 text-sm"><option value="INVOICE">Faturë</option><option value="ORDER">Porosi</option><option value="DELIVERY">Fletë-dalje</option><option value="RETURN">Kthim</option></select></label> : <div className="space-y-2"><label className="flex items-center gap-2 text-xs font-semibold text-[#3d5568]"><input type="checkbox" checked={form.active} onChange={event => setForm(current => ({ ...current, active: event.target.checked }))} />Aktive</label>{type === "cost-centers" && <label className="flex items-center gap-2 text-xs font-semibold text-[#3d5568]"><input type="checkbox" checked={form.mainProduction} onChange={event => setForm(current => ({ ...current, mainProduction: event.target.checked }))} />Qendra kryesore e prodhimit</label>}</div>}<div className="flex justify-end gap-2 border-t border-[#d1dbe2] pt-3"><Button type="button" variant="outline" onClick={() => setEditorOpen(false)}><X className="mr-1 h-4 w-4" />Anullo</Button><Button type="submit" className="bg-[#2b6892]" disabled={createIssuer.isPending || createDocumentGroup.isPending || createCostCenter.isPending}><FilePlus2 className="mr-1 h-4 w-4" />Ruaj</Button></div></form></DialogContent></Dialog>
  </AlphaCatalogWindow>;
}
