import { useMemo, useState } from "react";
import { Download, FileText, Plus, Printer, Search, Trash2, X } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { trpc } from "@/lib/trpc";
import { exportToExcel, exportToPDF } from "@/lib/export";
import { toast } from "sonner";

type CompanyRole = "owner" | "admin" | "user" | "viewer";
type CompanyUser = { id: number; name: string | null; email: string | null; globalRole: "admin" | "user"; companyRole: CompanyRole; createdAt: Date | string; lastSignedIn: Date | string };
type RegisteredUser = { id: number; name: string | null; email: string | null; globalRole: "admin" | "user" };
type ExportRow = { Përdoruesi: string; Email: string; "Roli global": string; "Roli në kompani": string; "Hyrja e fundit": string };
const columns: Array<{ key: keyof ExportRow; label: string }> = [{ key: "Përdoruesi", label: "Përdoruesi" }, { key: "Email", label: "Email" }, { key: "Roli global", label: "Roli global" }, { key: "Roli në kompani", label: "Roli në kompani" }, { key: "Hyrja e fundit", label: "Hyrja e fundit" }];
const companyRoleText: Record<CompanyRole, string> = { owner: "Pronar", admin: "Administrator", user: "Përdorues", viewer: "Lexues" };
const globalRoleText: Record<"admin" | "user", string> = { admin: "Administrator", user: "Përdorues" };
const editableRoles: Array<{ id: "admin" | "user" | "viewer"; label: string }> = [{ id: "admin", label: "Administrator" }, { id: "user", label: "Përdorues" }, { id: "viewer", label: "Lexues" }];
const dateText = (value: Date | string) => new Date(value).toLocaleString("sq-AL");
const roleClass = (role: CompanyRole) => role === "owner" ? "bg-amber-100 text-amber-800" : role === "admin" ? "bg-[#f2eaf1] text-[#714b67]" : role === "viewer" ? "bg-slate-100 text-slate-700" : "bg-blue-100 text-blue-800";
const escapeHtml = (value: string) => value.replace(/[&<>"']/g, char => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#039;" })[char] || char);
const rowsOf = (users: CompanyUser[]): ExportRow[] => users.map(user => ({ Përdoruesi: user.name || "—", Email: user.email || "—", "Roli global": globalRoleText[user.globalRole], "Roli në kompani": companyRoleText[user.companyRole], "Hyrja e fundit": dateText(user.lastSignedIn) }));

function printRows(rows: ExportRow[], title = "Përdoruesit dhe Rolet") {
  const popup = window.open("", "_blank", "width=1200,height=800");
  if (!popup) return;
  const header = columns.map(column => `<th>${escapeHtml(column.label)}</th>`).join("");
  const body = rows.map(row => `<tr>${columns.map(column => `<td>${escapeHtml(row[column.key])}</td>`).join("")}</tr>`).join("");
  popup.document.write(`<!doctype html><html lang="sq"><head><title>${escapeHtml(title)}</title><style>body{font-family:Arial,sans-serif;color:#332d33;padding:28px}h1{color:#714b67;font-size:22px;margin:0 0 18px}table{width:100%;border-collapse:collapse;font-size:12px}th{background:#714b67;color:#fff;text-align:left;padding:9px}td{border:1px solid #ded8df;padding:8px}@media print{body{padding:0}}</style></head><body><h1>${escapeHtml(title)}</h1><table><thead><tr>${header}</tr></thead><tbody>${body || `<tr><td colspan="${columns.length}">Nuk ka përdorues.</td></tr>`}</tbody></table><script>window.onload=()=>window.print()</script></body></html>`);
  popup.document.close();
}

function MemberManager({ companyId, memberIds }: { companyId: number; memberIds: number[] }) {
  const utils = trpc.useUtils();
  const [open, setOpen] = useState(false);
  const [search, setSearch] = useState("");
  const [role, setRole] = useState<"admin" | "user" | "viewer">("user");
  const resultsQuery = trpc.company.findUsers.useQuery({ companyId, search }, { enabled: open && search.trim().length >= 2 });
  const addUser = trpc.company.addUser.useMutation({ onSuccess: async () => { await utils.company.users.invalidate({ companyId }); toast.success("Përdoruesi u lidh me kompaninë."); setSearch(""); }, onError: error => toast.error(error.message) });
  const available = (resultsQuery.data as RegisteredUser[] | undefined)?.filter(user => !memberIds.includes(user.id)) || [];
  return <><Button size="sm" onClick={() => setOpen(true)} className="bg-[#714b67] text-white hover:bg-[#5f3d58]"><Plus className="mr-1.5 h-4 w-4" />Shto përdorues</Button>{open && <div className="fixed inset-0 z-[70] bg-slate-950/45"><section className="flex h-full w-full flex-col bg-[#f8f8f8]"><header className="flex items-center gap-3 border-b border-[#ded8df] bg-white px-4 py-3"><Button size="sm" variant="outline" onClick={() => { setOpen(false); setSearch(""); }}><X className="mr-1 h-4 w-4" />Mbyll</Button><h2 className="flex-1 text-lg font-semibold text-[#332d33]">Shto përdorues në kompani</h2></header><main className="mx-auto w-full max-w-4xl flex-1 overflow-y-auto p-5"><div className="rounded-md border border-[#ded8df] bg-white p-5"><div className="flex flex-wrap gap-2"><div className="relative min-w-[300px] flex-1"><Search className="absolute left-3 top-2.5 h-4 w-4 text-[#777]" /><Input value={search} onChange={event => setSearch(event.target.value)} className="pl-9" placeholder="Kërko emër ose email të përdoruesit…" autoFocus /></div><div className="flex gap-1">{editableRoles.map(choice => <button key={choice.id} type="button" onClick={() => setRole(choice.id)} className={`rounded px-3 py-2 text-sm font-semibold ${role === choice.id ? "bg-[#714b67] text-white" : "border border-[#ded8df] bg-white text-[#625c62]"}`}>{choice.label}</button>)}</div></div><div className="mt-4 divide-y divide-[#eee9ee] rounded border border-[#ded8df]">{search.trim().length < 2 ? <div className="px-4 py-8 text-center text-sm text-[#777]">Shkruaj së paku dy karaktere për të kërkuar përdorues të regjistruar.</div> : resultsQuery.isLoading ? <div className="px-4 py-8 text-center text-sm text-[#777]">Po kërkohen përdoruesit…</div> : available.length ? available.map(user => <div key={user.id} className="flex flex-wrap items-center gap-3 px-4 py-3"><div className="min-w-0 flex-1"><p className="truncate font-semibold text-[#332d33]">{user.name || "—"}</p><p className="truncate text-sm text-[#625c62]">{user.email || "—"}</p></div><span className="rounded bg-slate-100 px-2 py-1 text-xs text-slate-700">{globalRoleText[user.globalRole]}</span><Button size="sm" disabled={addUser.isPending} onClick={() => addUser.mutate({ companyId, userId: user.id, role })}>Shto</Button></div>) : <div className="px-4 py-8 text-center text-sm text-[#777]">Nuk u gjet përdorues i lirë për lidhje.</div>}</div></div></main></section></div>}</>;
}

function UserDetail({ user, companyId, onClose }: { user: CompanyUser; companyId: number; onClose: () => void }) {
  const utils = trpc.useUtils();
  const setRole = trpc.company.setUserRole.useMutation({ onSuccess: async () => { await utils.company.users.invalidate({ companyId }); toast.success("Roli në kompani u përditësua."); }, onError: error => toast.error(error.message) });
  const removeUser = trpc.company.removeUser.useMutation({ onSuccess: async () => { await utils.company.users.invalidate({ companyId }); toast.success("Përdoruesi u hoq nga kompania."); onClose(); }, onError: error => toast.error(error.message) });
  const rows = rowsOf([user]);
  const setUserRole = (role: "admin" | "user" | "viewer") => { if (role !== user.companyRole && window.confirm(`Të caktohet roli ${companyRoleText[role]}?`)) setRole.mutate({ companyId, userId: user.id, role }); };
  const remove = () => { if (window.confirm(`Të hiqet ${user.name || user.email || "përdoruesi"} nga kompania?`)) removeUser.mutate({ companyId, userId: user.id }); };
  return <div className="fixed inset-0 z-[70] bg-slate-950/45"><section className="flex h-full w-full flex-col bg-[#f8f8f8]"><header className="flex flex-wrap items-center gap-2 border-b border-[#ded8df] bg-white px-4 py-3"><Button size="sm" variant="outline" onClick={onClose}><X className="mr-1 h-4 w-4" />Mbyll</Button><h2 className="min-w-0 flex-1 truncate text-lg font-semibold text-[#332d33]">{user.name || user.email || "Përdorues"}</h2>{user.companyRole !== "owner" && <Button size="sm" variant="outline" disabled={removeUser.isPending} onClick={remove} className="border-red-200 text-red-700 hover:bg-red-50"><Trash2 className="mr-1 h-4 w-4" />Hiq</Button>}<Button size="sm" variant="outline" onClick={() => exportToExcel(rows, "Perdoruesi", "Përdoruesi", columns)}><Download className="mr-1 h-4 w-4" />Excel</Button><Button size="sm" variant="outline" onClick={() => exportToPDF(rows, "Perdoruesi", "Përdoruesi", columns)}><FileText className="mr-1 h-4 w-4" />PDF</Button><Button size="sm" variant="outline" onClick={() => printRows(rows, user.name || "Përdoruesi")}><Printer className="mr-1 h-4 w-4" />Print Preview</Button></header><main className="mx-auto grid w-full max-w-5xl flex-1 content-start gap-5 overflow-y-auto p-5 md:grid-cols-[0.4fr_0.6fr]"><section className="rounded-md border border-[#ded8df] bg-white p-5"><p className="text-xs font-semibold uppercase tracking-wide text-[#777]">Përdoruesi</p><p className="mt-2 text-lg font-semibold text-[#332d33]">{user.name || "—"}</p><p className="mt-1 text-sm text-[#625c62]">{user.email || "—"}</p><div className="mt-5 space-y-2 text-sm"><p><span className="text-[#777]">Roli global: </span>{globalRoleText[user.globalRole]}</p><p><span className="text-[#777]">Hyrja e fundit: </span>{dateText(user.lastSignedIn)}</p></div></section><section className="rounded-md border border-[#ded8df] bg-white p-5"><p className="text-xs font-semibold uppercase tracking-wide text-[#777]">Roli në kompani</p><div className="mt-3 flex flex-wrap gap-2">{user.companyRole === "owner" ? <span className={`rounded px-3 py-2 text-sm font-semibold ${roleClass(user.companyRole)}`}>Pronar</span> : editableRoles.map(choice => <button type="button" key={choice.id} disabled={setRole.isPending} onClick={() => setUserRole(choice.id)} className={`rounded px-3 py-2 text-sm font-semibold ${choice.id === user.companyRole ? roleClass(user.companyRole) : "border border-[#ded8df] bg-white text-[#625c62] hover:bg-[#f7f0f6]"}`}>{choice.label}</button>)}</div></section></main></section></div>;
}

export default function UsersRoles({ companyId }: { companyId: number }) {
  const { data, isLoading, error } = trpc.company.users.useQuery({ companyId });
  const [search, setSearch] = useState("");
  const [selected, setSelected] = useState<CompanyUser>();
  const users = data as CompanyUser[] | undefined;
  const visible = useMemo(() => { const term = search.trim().toLocaleLowerCase("sq-AL"); return (users || []).filter(user => !term || [user.name, user.email, user.globalRole, companyRoleText[user.companyRole]].some(value => value?.toLocaleLowerCase("sq-AL").includes(term))); }, [users, search]);
  const rows = useMemo(() => rowsOf(visible), [visible]);
  return <section className="space-y-4"><header className="flex flex-col gap-3 border-b border-[#ded8df] pb-4 md:flex-row md:items-center md:justify-between"><h1 className="text-xl font-semibold text-[#332d33]">Përdoruesit dhe Rolet</h1><div className="flex flex-wrap items-center gap-2"><MemberManager companyId={companyId} memberIds={(users || []).map(user => user.id)} /><Button size="sm" variant="outline" disabled={!rows.length} onClick={() => exportToExcel(rows, "Perdoruesit-dhe-Rolet", "Përdoruesit", columns)}><Download className="mr-1.5 h-4 w-4" />Excel</Button><Button size="sm" variant="outline" disabled={!rows.length} onClick={() => exportToPDF(rows, "Perdoruesit-dhe-Rolet", "Përdoruesit dhe Rolet", columns)}><FileText className="mr-1.5 h-4 w-4" />PDF</Button><Button size="sm" variant="outline" disabled={!rows.length} onClick={() => printRows(rows)}><Printer className="mr-1.5 h-4 w-4" />Print Preview</Button><div className="relative min-w-[280px]"><Search className="absolute left-3 top-2.5 h-4 w-4 text-[#777]" /><Input value={search} onChange={event => setSearch(event.target.value)} className="h-9 bg-white pl-9" placeholder="Kërko përdorues ose rol…" /></div></div></header>{error ? <div className="rounded-md border border-red-200 bg-red-50 p-4 text-sm text-red-700">{error.message}</div> : <div className="overflow-x-auto rounded-md border border-[#ded8df] bg-white"><table className="w-full min-w-[900px] text-sm"><thead className="bg-[#f8f7f8] text-left text-xs font-semibold uppercase tracking-wide text-[#625c62]"><tr>{columns.map(column => <th key={column.key} className="px-4 py-3">{column.label}</th>)}</tr></thead><tbody>{isLoading ? <tr><td colSpan={columns.length} className="p-10 text-center text-[#777]">Po ngarkohen përdoruesit…</td></tr> : visible.length === 0 ? <tr><td colSpan={columns.length} className="p-10 text-center text-[#777]">Nuk ka përdorues që përputhen.</td></tr> : visible.map(user => <tr className="border-t border-[#eee9ee]" key={user.id}><td className="px-4 py-3"><button onClick={() => setSelected(user)} className="font-semibold text-[#714b67] underline-offset-2 hover:underline">{user.name || "—"}</button></td><td className="px-4 py-3">{user.email || "—"}</td><td className="px-4 py-3">{globalRoleText[user.globalRole]}</td><td className="px-4 py-3"><span className={`rounded px-2 py-1 text-xs font-semibold ${roleClass(user.companyRole)}`}>{companyRoleText[user.companyRole]}</span></td><td className="px-4 py-3">{dateText(user.lastSignedIn)}</td></tr>)}</tbody></table></div>}{selected && <UserDetail user={selected} companyId={companyId} onClose={() => setSelected(undefined)} />}</section>;
}
