export type ReportModule = "Blerje" | "Shitje" | "Magazina" | "Kontabilitet" | "CRM" | "Banka";

export type ReportCatalogItem = {
  key: string;
  module: ReportModule;
  group: string;
  title: string;
  description: string;
  baseKey?: string;
};

type ReportSeed = readonly [key: string, group: string, title: string, baseKey?: string];

const makeModuleReports = (module: ReportModule, reports: readonly ReportSeed[]): ReportCatalogItem[] => reports.map(([key, group, title, baseKey]) => ({
  key,
  module,
  group,
  title,
  description: `${title}. Raport i filtrueshëm sipas periudhës së zgjedhur.`,
  baseKey,
}));

/** Katalogu i plotë Odoo-style: saktësisht 20 raporte për secilin modul ERP. */
export const REPORT_CATALOG: ReportCatalogItem[] = [
  ...makeModuleReports("Blerje", [
    ["purchase_summary_register_pdf", "Kryesore", "Regjistri përmbledhës i blerjeve"],
    ["purchase_invoices", "Kryesore", "Regjistri analitik i blerjeve"],
    ["purchase_document_register", "Kryesore", "Libri i blerjeve 2019", "purchase_invoices"],
    ["purchase_product_card_alpha", "Kryesore", "Kartela e artikullit", "purchase_invoices"],
    ["purchase_items_detail_alpha", "Kryesore", "Artikuj të blerë me detajime", "purchase_receipts"],
    ["purchase_items_expiry_alpha", "Kryesore", "Artikuj të blerë sipas datë skadencave dhe serisë", "purchase_receipts"],
    ["purchase_customs_import_register_pdf", "Kryesore", "Regjistri i doganimeve të importit"],
    ["purchase_items_alpha", "Kryesore", "Artikuj të blerë", "purchase_invoices"],
    ["purchase_items_by_branch_alpha", "Kryesore", "Artikuj të blerë sipas degëve administrative", "purchase_invoices"],
    ["purchase_analytic_register_format2_alpha", "Kryesore", "Regjistri analitik i blerjeve (Format 2)", "purchase_invoices"],
    ["purchase_contract_conversion_alpha", "Kryesore", "Konvertimi i kontratave të blerjes", "purchase_orders"],
    ["purchase_analytic_register_format3_alpha", "Kryesore", "Regjistri analitik i blerjeve (Format 3)", "purchase_invoices"],
    ["purchase_analytic_alpha", "Kryesore", "Blerje analitike", "purchase_suppliers"],
    ["purchase_product_card_format2_alpha", "Kryesore", "Kartela e artikullit (format 2)", "purchase_invoices"],
    ["purchase_analytic_detail_alpha", "Kryesore", "Regjistri analitik i blerjeve me detajime", "purchase_receipts"],
    ["purchase_monthly_ledger_alpha", "Kryesore", "Libri i blerjeve sipas muajve", "purchase_spend_trend"],
    ["purchase_price_list_alpha", "Kryesore", "Listë çmimesh blerje", "purchase_suppliers"],
    ["purchase_invoice_payment_register_pdf", "Kryesore", "Eksportimi i faturave të blerjeve"],
  ]),
  ...makeModuleReports("Shitje", [
    ["sales_invoices", "Dokumente", "Faturat e shitjes"],
    ["sales_quotations", "Dokumente", "Ofertat"],
    ["sales_orders", "Dokumente", "Porositë e shitjes"],
    ["sales_deliveries", "Logjistikë", "Fletë-daljet"],
    ["sales_returns", "Logjistikë", "Kthimet nga klientët"],
    ["sales_customers", "Klientë", "Të ardhurat sipas klientit"],
    ["sales_invoice_status", "Dokumente", "Statusi i faturave", "sales_invoices"],
    ["sales_invoices_today", "Analizë", "Faturat e sotme", "sales_invoices"],
    ["sales_invoice_volume", "Analizë", "Vëllimi i faturimit", "sales_invoices"],
    ["sales_open_invoices", "Dokumente", "Faturat e hapura", "sales_invoices"],
    ["sales_quotation_status", "Dokumente", "Statusi i ofertave", "sales_quotations"],
    ["sales_quotation_register", "Dokumente", "Regjistri i ofertave", "sales_quotations"],
    ["sales_orders_open", "Dokumente", "Porositë e hapura", "sales_orders"],
    ["sales_orders_status", "Dokumente", "Statusi i porosive", "sales_orders"],
    ["sales_delivery_status", "Logjistikë", "Statusi i dërgesave", "sales_deliveries"],
    ["sales_delivery_register", "Logjistikë", "Regjistri i dërgesave", "sales_deliveries"],
    ["sales_returns_analysis", "Logjistikë", "Analiza e kthimeve", "sales_returns"],
    ["sales_top_customers", "Klientë", "Klientët kryesorë", "sales_customers"],
    ["sales_customer_statement", "Klientë", "Pasqyra e klientëve", "sales_customers"],
    ["sales_revenue_trend", "Analizë", "Trendi i të ardhurave", "sales_invoices"],
    ["sales_quantity_total_pdf", "Formate referencë", "Shitjet sipas sasisë totale"],
    ["sales_items_sold_pdf", "Formate referencë", "Artikuj të shitur"],
    ["sales_unsold_items_pdf", "Formate referencë", "Artikuj të pashitur"],
    ["sales_summary_register_pdf", "Formate referencë", "Regjistri përmbledhës i shitjeve"],
    ["sales_by_city_pdf", "Formate referencë", "Shitjet sipas qyteteve"],
    ["sales_by_customer_pdf", "Formate referencë", "Shitjet sipas klientëve"],
    ["sales_quantity_pdf", "Formate referencë", "Shitjet sipas sasisë"],
    ["sales_discount_analysis_pdf", "Formate referencë", "Artikujt me zbritje analitike"],
    ["sales_product_card_pdf", "Formate referencë", "Kartela e artikullit të shitjes"],
    ["sales_returns_pdf", "Formate referencë", "Regjistri i kthimeve"],
    ["sales_price_list_pdf", "Formate referencë", "Lista e çmimeve të shitjes"],
    ["sales_comparison_pdf", "Formate referencë", "Paragona e shitjeve"],
    ["sales_analytic_register_pdf", "Formate referencë", "Regjistri analitik i shitjeve"],
    ["sales_margin_pdf", "Formate referencë", "Marzhi i shitjeve"],
    ["sales_margin_detail_pdf", "Formate referencë", "Marzhi i shitjeve — Formati 2"],
    ["sales_by_product_pdf", "Formate referencë", "Shitjet sipas artikujve"],
  ]),
  ...makeModuleReports("Magazina", [
    ["inventory_analytic_register_pdf", "Kryesore", "Regjistri përmbledhës i magazinës"],
    ["inventory_warehouse_status_pdf", "Kryesore", "Regjistri analitik i magazinës"],
    ["inventory_product_summary_pdf", "Kryesore", "Gjendja e magazinës"],
    ["inventory_product_card_pdf", "Kryesore", "Kartela e artikullit"],
    ["inventory_stock_summary", "Kryesore", "Gjendja e përmbledhur e artikujve", "inventory_stock"],
    ["inventory_negative_stock", "Kryesore", "Artikuj me gjendje negative", "inventory_stock"],
    ["inventory_stock", "Kryesore", "Maturimi i stokut"],
    ["inventory_minimum_status_pdf", "Kryesore", "Gjendja e artikujve minimum dhe maksimum"],
    ["inventory_balances", "Kryesore", "Maturimi përmbledhes i stokut"],
    ["inventory_warehouse_detail_pdf", "Kryesore", "Gjendja e magazinës sipas detajimeve të artikujve"],
    ["inventory_stock_by_location", "Kryesore", "Gjendja e magazines sipas date skadences dhe serise", "inventory_balances"],
    ["inventory_transfers", "Kryesore", "Gjendja e Rezervuar e Artikujve"],
    ["inventory_transfer_status", "Kryesore", "Ekzekutimi i Rezervimeve", "inventory_transfers"],
    ["inventory_stock_by_product", "Kryesore", "Gjendja e artikujve", "inventory_stock"],
    ["inventory_value_by_product", "Kryesore", "Gjendja e Artikullit sipas Magazines", "inventory_balances"],
    ["inventory_movements", "Kryesore", "Raport Hyrje"],
    ["inventory_valuation", "Kryesore", "Gjendja dhe cmimet e shitjes se artikujve"],
    ["inventory_adjustment_register", "Kryesore", "Lista e artikujve me detajime", "inventory_stock"],
    ["inventory_adjustments", "Kryesore", "Kartela e artikullit me detajime", "inventory_stock"],
    ["inventory_warehouse_detail_value", "Kryesore", "Gjendja e magazines ne vlefte", "inventory_valuation"],
    ["inventory_composite_stock", "Kryesore", "Gjendja e artikujve te perbere", "inventory_stock"],
    ["inventory_long_term_serials", "Kryesore", "Gjendja e magazines sipas serialeve te artikujve afatgjate", "inventory_stock"],
    ["inventory_simple_product_card", "Kryesore", "Kartela e thjeshte e artikullit", "inventory_product_card_pdf"],
  ]),
  ...makeModuleReports("Kontabilitet", [
    ["accounting_trial_balance", "Pasqyrat financiare", "Bilanci i provës"],
    ["accounting_profit_loss", "Pasqyrat financiare", "Fitim / Humbje"],
    ["accounting_payments", "Pagesa", "Pagesat"],
    ["accounting_taxes", "Tatime", "Normat e TVSH-së"],
    ["accounting_journals", "Regjistrime", "Ditarët dhe regjistrimet"],
    ["accounting_balance_sheet", "Pasqyrat financiare", "Bilanci kontabël", "accounting_trial_balance"],
    ["accounting_general_ledger", "Regjistrime", "Libri kryesor", "accounting_journals"],
    ["accounting_journal_entries", "Regjistrime", "Regjistrimet e ditarit", "accounting_journals"],
    ["accounting_journal_status", "Regjistrime", "Statusi i regjistrimeve", "accounting_journals"],
    ["accounting_payment_inbound", "Pagesa", "Arkëtimet", "accounting_payments"],
    ["accounting_payment_outbound", "Pagesa", "Pagesat dalëse", "accounting_payments"],
    ["accounting_payment_status", "Pagesa", "Statusi i pagesave", "accounting_payments"],
    ["accounting_tax_summary", "Tatime", "Përmbledhja e TVSH-së", "accounting_taxes"],
    ["accounting_active_taxes", "Tatime", "TVSH aktive", "accounting_taxes"],
    ["accounting_revenue_summary", "Pasqyrat financiare", "Përmbledhja e të ardhurave", "accounting_profit_loss"],
    ["accounting_expense_summary", "Pasqyrat financiare", "Përmbledhja e shpenzimeve", "accounting_profit_loss"],
    ["accounting_net_result", "Pasqyrat financiare", "Rezultati neto", "accounting_profit_loss"],
    ["accounting_debit_credit", "Pasqyrat financiare", "Debi dhe kredi", "accounting_trial_balance"],
    ["accounting_account_register", "Regjistrime", "Regjistri i llogarive", "accounting_trial_balance"],
    ["accounting_payment_register", "Pagesa", "Regjistri i pagesave", "accounting_payments"],
  ]),
  ...makeModuleReports("CRM", [
    ["partner_customer_situation_pdf", "Kryesore", "Situacioni i klientit"],
    ["partner_supplier_situation_pdf", "Kryesore", "Situacioni i furnitorit"],
    ["partner_customer_card_pdf", "Kryesore", "Kartela e klientit"],
    ["partner_supplier_card_pdf", "Kryesore", "Kartela e Furnitorit"],
    ["partner_customer_card_base_pdf", "Kryesore", "Kartela e klientit në monedhë bazë"],
    ["partner_supplier_card_base_pdf", "Kryesore", "Kartela e furnitorit në monedhë bazë"],
    ["partner_billing_payment_register_pdf", "Kryesore", "Regjistri përmbledhës faturime dhe pagesa"],
  ]),
  ...makeModuleReports("Banka", [
    ["bank_balances", "Llogaritë", "Balancat bankare"],
    ["bank_statements", "Ekstraktet", "Ekstraktet bankare"],
    ["bank_transactions", "Transaksionet", "Transaksionet bankare"],
    ["bank_reconciliation", "Pajtimi", "Pajtimi bankar"],
    ["bank_transfers", "Transferta", "Transfertat bankare"],
    ["bank_account_register", "Llogaritë", "Regjistri i llogarive", "bank_balances"],
    ["bank_account_balances", "Llogaritë", "Balanca sipas llogarisë", "bank_balances"],
    ["bank_statement_status", "Ekstraktet", "Statusi i ekstrakteve", "bank_statements"],
    ["bank_statement_register", "Ekstraktet", "Regjistri i ekstrakteve", "bank_statements"],
    ["bank_transactions_in", "Transaksionet", "Hyrjet bankare", "bank_transactions"],
    ["bank_transactions_out", "Transaksionet", "Daljet bankare", "bank_transactions"],
    ["bank_transactions_status", "Transaksionet", "Statusi i transaksioneve", "bank_transactions"],
    ["bank_unreconciled", "Pajtimi", "Transaksionet e papajtuara", "bank_reconciliation"],
    ["bank_reconciled_register", "Pajtimi", "Regjistri i pajtimit", "bank_transactions"],
    ["bank_transfer_status", "Transferta", "Statusi i transfertave", "bank_transfers"],
    ["bank_transfer_register", "Transferta", "Regjistri i transfertave", "bank_transfers"],
    ["bank_cash_flow", "Analizë", "Fluksi i parasë", "bank_transactions"],
    ["bank_incoming_summary", "Analizë", "Përmbledhja e hyrjeve", "bank_transactions"],
    ["bank_outgoing_summary", "Analizë", "Përmbledhja e daljeve", "bank_transactions"],
    ["bank_reconciliation_summary", "Pajtimi", "Përmbledhja e pajtimit", "bank_reconciliation"],
  ]),
];

export const REPORT_BASE_KEYS: Record<string, string> = Object.fromEntries(REPORT_CATALOG.map(item => [item.key, item.baseKey ?? item.key]));

export const REPORTS_BY_MODULE: Record<ReportModule, ReportCatalogItem[]> = {
  Blerje: REPORT_CATALOG.filter(item => item.module === "Blerje"),
  Shitje: REPORT_CATALOG.filter(item => item.module === "Shitje"),
  Magazina: REPORT_CATALOG.filter(item => item.module === "Magazina"),
  Kontabilitet: REPORT_CATALOG.filter(item => item.module === "Kontabilitet"),
  CRM: REPORT_CATALOG.filter(item => item.module === "CRM"),
  Banka: REPORT_CATALOG.filter(item => item.module === "Banka"),
};
