export type ReportModule = "Blerje" | "Shitje" | "Magazina" | "Kontabilitet" | "CRM" | "Banka";

export type ReportCatalogItem = {
  key: string;
  module: ReportModule;
  group: string;
  title: string;
  description: string;
  baseKey?: string;
};

type ReportSeed = readonly [key: string, group: string, title: string, baseKey?: string];

const makeModuleReports = (module: ReportModule, reports: readonly ReportSeed[]): ReportCatalogItem[] => reports.map(([key, group, title, baseKey]) => ({
  key,
  module,
  group,
  title,
  description: `${title}. Raport i filtrueshëm sipas periudhës së zgjedhur.`,
  baseKey,
}));

/** Katalogu i plotë Odoo-style: saktësisht 20 raporte për secilin modul ERP. */
export const REPORT_CATALOG: ReportCatalogItem[] = [
  ...makeModuleReports("Blerje", [
    ["purchase_invoices", "Dokumente", "Faturat e blerjes"],
    ["purchase_orders", "Dokumente", "Porositë e blerjes"],
    ["purchase_receipts", "Logjistikë", "Pranimet e mallit"],
    ["purchase_returns", "Logjistikë", "Kthimet te furnitorët"],
    ["purchase_suppliers", "Furnitorë", "Shpenzimi sipas furnitorit"],
    ["purchase_invoice_status", "Dokumente", "Statusi i faturave", "purchase_invoices"],
    ["purchase_open_invoices", "Dokumente", "Faturat e hapura", "purchase_invoices"],
    ["purchase_invoice_volume", "Analizë", "Vëllimi i faturave", "purchase_invoices"],
    ["purchase_supplier_statement", "Furnitorë", "Pasqyra e furnitorëve", "purchase_suppliers"],
    ["purchase_top_suppliers", "Furnitorë", "Furnitorët kryesorë", "purchase_suppliers"],
    ["purchase_orders_open", "Dokumente", "Porositë e hapura", "purchase_orders"],
    ["purchase_orders_status", "Dokumente", "Statusi i porosive", "purchase_orders"],
    ["purchase_receipts_by_supplier", "Logjistikë", "Pranimet sipas furnitorit", "purchase_receipts"],
    ["purchase_receipts_timeline", "Logjistikë", "Kalendari i pranimeve", "purchase_receipts"],
    ["purchase_returns_analysis", "Logjistikë", "Analiza e kthimeve", "purchase_returns"],
    ["purchase_returns_status", "Logjistikë", "Statusi i kthimeve", "purchase_returns"],
    ["purchase_spend_trend", "Analizë", "Trendi i shpenzimeve", "purchase_invoices"],
    ["purchase_supplier_count", "Furnitorë", "Furnitorë aktivë", "purchase_suppliers"],
    ["purchase_document_register", "Dokumente", "Regjistri i blerjeve", "purchase_invoices"],
    ["purchase_receipt_control", "Logjistikë", "Kontrolli i pranimeve", "purchase_receipts"],
    ["purchase_supplier_card_pdf", "Formate referencë", "Kartela e furnitorit"],
    ["purchase_supplier_card_format3_pdf", "Formate referencë", "Kartela e furnitorit — Formati 3"],
    ["purchase_supplier_maturity_pdf", "Formate referencë", "Furnitorët me maturim"],
    ["purchase_supplier_maturity_summary_pdf", "Formate referencë", "Maturimi përmbledhës i furnitorëve"],
    ["purchase_supplier_situation_category_pdf", "Formate referencë", "Situacioni i furnitorëve sipas kategorive"],
    ["purchase_customs_import_register_pdf", "Formate referencë", "Regjistri i doganimit të importeve"],
    ["purchase_invoice_payment_register_pdf", "Formate referencë", "Faturime dhe pagesa"],
  ]),
  ...makeModuleReports("Shitje", [
    ["sales_invoices", "Dokumente", "Faturat e shitjes"],
    ["sales_quotations", "Dokumente", "Ofertat"],
    ["sales_orders", "Dokumente", "Porositë e shitjes"],
    ["sales_deliveries", "Logjistikë", "Fletë-daljet"],
    ["sales_returns", "Logjistikë", "Kthimet nga klientët"],
    ["sales_customers", "Klientë", "Të ardhurat sipas klientit"],
    ["sales_invoice_status", "Dokumente", "Statusi i faturave", "sales_invoices"],
    ["sales_invoices_today", "Analizë", "Faturat e sotme", "sales_invoices"],
    ["sales_invoice_volume", "Analizë", "Vëllimi i faturimit", "sales_invoices"],
    ["sales_open_invoices", "Dokumente", "Faturat e hapura", "sales_invoices"],
    ["sales_quotation_status", "Dokumente", "Statusi i ofertave", "sales_quotations"],
    ["sales_quotation_register", "Dokumente", "Regjistri i ofertave", "sales_quotations"],
    ["sales_orders_open", "Dokumente", "Porositë e hapura", "sales_orders"],
    ["sales_orders_status", "Dokumente", "Statusi i porosive", "sales_orders"],
    ["sales_delivery_status", "Logjistikë", "Statusi i dërgesave", "sales_deliveries"],
    ["sales_delivery_register", "Logjistikë", "Regjistri i dërgesave", "sales_deliveries"],
    ["sales_returns_analysis", "Logjistikë", "Analiza e kthimeve", "sales_returns"],
    ["sales_top_customers", "Klientë", "Klientët kryesorë", "sales_customers"],
    ["sales_customer_statement", "Klientë", "Pasqyra e klientëve", "sales_customers"],
    ["sales_revenue_trend", "Analizë", "Trendi i të ardhurave", "sales_invoices"],
    ["sales_quantity_total_pdf", "Formate referencë", "Shitjet sipas sasisë totale"],
    ["sales_items_sold_pdf", "Formate referencë", "Artikuj të shitur"],
    ["sales_unsold_items_pdf", "Formate referencë", "Artikuj të pashitur"],
    ["sales_summary_register_pdf", "Formate referencë", "Regjistri përmbledhës i shitjeve"],
    ["sales_by_city_pdf", "Formate referencë", "Shitjet sipas qyteteve"],
    ["sales_by_customer_pdf", "Formate referencë", "Shitjet sipas klientëve"],
    ["sales_quantity_pdf", "Formate referencë", "Shitjet sipas sasisë"],
    ["sales_discount_analysis_pdf", "Formate referencë", "Artikujt me zbritje analitike"],
    ["sales_product_card_pdf", "Formate referencë", "Kartela e artikullit të shitjes"],
    ["sales_returns_pdf", "Formate referencë", "Regjistri i kthimeve"],
    ["sales_price_list_pdf", "Formate referencë", "Lista e çmimeve të shitjes"],
    ["sales_comparison_pdf", "Formate referencë", "Paragona e shitjeve"],
    ["sales_analytic_register_pdf", "Formate referencë", "Regjistri analitik i shitjeve"],
    ["sales_margin_pdf", "Formate referencë", "Marzhi i shitjeve"],
    ["sales_margin_detail_pdf", "Formate referencë", "Marzhi i shitjeve — Formati 2"],
    ["sales_by_product_pdf", "Formate referencë", "Shitjet sipas artikujve"],
  ]),
  ...makeModuleReports("Magazina", [
    ["inventory_stock", "Gjendja e stokut", "Gjendja e stokut"],
    ["inventory_balances", "Gjendja e stokut", "Stoku sipas magazine"],
    ["inventory_movements", "Lëvizje", "Lëvizjet e stokut"],
    ["inventory_low_stock", "Analizë", "Stoku i ulët"],
    ["inventory_transfers", "Lëvizje", "Transfertat e magazinës"],
    ["inventory_adjustments", "Inventarizim", "Inventarizimet"],
    ["inventory_valuation", "Vlerësim", "Vlera e stokut"],
    ["inventory_stock_by_product", "Gjendja e stokut", "Stoku sipas artikullit", "inventory_stock"],
    ["inventory_stock_by_location", "Gjendja e stokut", "Stoku sipas lokacionit", "inventory_balances"],
    ["inventory_negative_stock", "Analizë", "Stoku negativ", "inventory_stock"],
    ["inventory_reorder_alert", "Analizë", "Alarmi i rimbushjes", "inventory_low_stock"],
    ["inventory_movement_in", "Lëvizje", "Hyrjet në stok", "inventory_movements"],
    ["inventory_movement_out", "Lëvizje", "Daljet nga stoku", "inventory_movements"],
    ["inventory_transfer_status", "Lëvizje", "Statusi i transfertave", "inventory_transfers"],
    ["inventory_transfer_register", "Lëvizje", "Regjistri i transfertave", "inventory_transfers"],
    ["inventory_adjustment_status", "Inventarizim", "Statusi i inventarizimeve", "inventory_adjustments"],
    ["inventory_adjustment_register", "Inventarizim", "Regjistri i inventarizimeve", "inventory_adjustments"],
    ["inventory_value_by_product", "Vlerësim", "Vlera sipas artikullit", "inventory_valuation"],
    ["inventory_stock_summary", "Analizë", "Përmbledhja e stokut", "inventory_stock"],
    ["inventory_movement_register", "Lëvizje", "Regjistri i lëvizjeve", "inventory_movements"],
    ["inventory_warehouse_status_pdf", "Formate referencë", "Gjendja e magazinës"],
    ["inventory_analytic_register_pdf", "Formate referencë", "Regjistri analitik i magazinës"],
    ["inventory_product_summary_pdf", "Formate referencë", "Gjendja e artikullit — Përmbledhur"],
    ["inventory_article_analysis_pdf", "Formate referencë", "Analiza e artikujve"],
    ["inventory_minimum_status_pdf", "Formate referencë", "Gjendja e artikujve minimum"],
    ["inventory_warehouse_detail_pdf", "Formate referencë", "Gjendja e magazinës sipas detajeve"],
    ["inventory_product_card_pdf", "Formate referencë", "Kartela e artikullit"],
  ]),
  ...makeModuleReports("Kontabilitet", [
    ["accounting_trial_balance", "Pasqyrat financiare", "Bilanci i provës"],
    ["accounting_profit_loss", "Pasqyrat financiare", "Fitim / Humbje"],
    ["accounting_payments", "Pagesa", "Pagesat"],
    ["accounting_taxes", "Tatime", "Normat e TVSH-së"],
    ["accounting_journals", "Regjistrime", "Ditarët dhe regjistrimet"],
    ["accounting_balance_sheet", "Pasqyrat financiare", "Bilanci kontabël", "accounting_trial_balance"],
    ["accounting_general_ledger", "Regjistrime", "Libri kryesor", "accounting_journals"],
    ["accounting_journal_entries", "Regjistrime", "Regjistrimet e ditarit", "accounting_journals"],
    ["accounting_journal_status", "Regjistrime", "Statusi i regjistrimeve", "accounting_journals"],
    ["accounting_payment_inbound", "Pagesa", "Arkëtimet", "accounting_payments"],
    ["accounting_payment_outbound", "Pagesa", "Pagesat dalëse", "accounting_payments"],
    ["accounting_payment_status", "Pagesa", "Statusi i pagesave", "accounting_payments"],
    ["accounting_tax_summary", "Tatime", "Përmbledhja e TVSH-së", "accounting_taxes"],
    ["accounting_active_taxes", "Tatime", "TVSH aktive", "accounting_taxes"],
    ["accounting_revenue_summary", "Pasqyrat financiare", "Përmbledhja e të ardhurave", "accounting_profit_loss"],
    ["accounting_expense_summary", "Pasqyrat financiare", "Përmbledhja e shpenzimeve", "accounting_profit_loss"],
    ["accounting_net_result", "Pasqyrat financiare", "Rezultati neto", "accounting_profit_loss"],
    ["accounting_debit_credit", "Pasqyrat financiare", "Debi dhe kredi", "accounting_trial_balance"],
    ["accounting_account_register", "Regjistrime", "Regjistri i llogarive", "accounting_trial_balance"],
    ["accounting_payment_register", "Pagesa", "Regjistri i pagesave", "accounting_payments"],
  ]),
  ...makeModuleReports("CRM", [
    ["crm_pipeline", "Pipeline", "Pipeline CRM"],
    ["crm_leads", "Pipeline", "Lead-et dhe opportunity"],
    ["crm_activities", "Aktivitete", "Aktivitetet CRM"],
    ["crm_won", "Performancë", "Mundësitë e fituara"],
    ["crm_leads_register", "Pipeline", "Regjistri i lead-eve", "crm_leads"],
    ["crm_opportunities", "Pipeline", "Opportunity aktive", "crm_leads"],
    ["crm_lead_status", "Pipeline", "Statusi i lead-eve", "crm_leads"],
    ["crm_pipeline_value", "Pipeline", "Vlera e pipeline-it", "crm_pipeline"],
    ["crm_pipeline_forecast", "Pipeline", "Parashikimi i shitjeve", "crm_pipeline"],
    ["crm_won_revenue", "Performancë", "Të ardhurat e fituara", "crm_won"],
    ["crm_won_register", "Performancë", "Regjistri i fitoreve", "crm_won"],
    ["crm_lost_opportunities", "Performancë", "Mundësitë e humbura", "crm_leads"],
    ["crm_activity_schedule", "Aktivitete", "Kalendari i aktiviteteve", "crm_activities"],
    ["crm_activity_status", "Aktivitete", "Statusi i aktiviteteve", "crm_activities"],
    ["crm_overdue_activities", "Aktivitete", "Aktivitetet e vonuara", "crm_activities"],
    ["crm_contact_register", "Kontaktet", "Regjistri i kontakteve", "crm_leads"],
    ["crm_conversion_analysis", "Analizë", "Analiza e konvertimeve", "crm_leads"],
    ["crm_probability_analysis", "Analizë", "Analiza e probabilitetit", "crm_leads"],
    ["crm_stage_analysis", "Analizë", "Analiza sipas fazës", "crm_pipeline"],
    ["crm_performance_summary", "Performancë", "Përmbledhja e performancës", "crm_pipeline"],
  ]),
  ...makeModuleReports("Banka", [
    ["bank_balances", "Llogaritë", "Balancat bankare"],
    ["bank_statements", "Ekstraktet", "Ekstraktet bankare"],
    ["bank_transactions", "Transaksionet", "Transaksionet bankare"],
    ["bank_reconciliation", "Pajtimi", "Pajtimi bankar"],
    ["bank_transfers", "Transferta", "Transfertat bankare"],
    ["bank_account_register", "Llogaritë", "Regjistri i llogarive", "bank_balances"],
    ["bank_account_balances", "Llogaritë", "Balanca sipas llogarisë", "bank_balances"],
    ["bank_statement_status", "Ekstraktet", "Statusi i ekstrakteve", "bank_statements"],
    ["bank_statement_register", "Ekstraktet", "Regjistri i ekstrakteve", "bank_statements"],
    ["bank_transactions_in", "Transaksionet", "Hyrjet bankare", "bank_transactions"],
    ["bank_transactions_out", "Transaksionet", "Daljet bankare", "bank_transactions"],
    ["bank_transactions_status", "Transaksionet", "Statusi i transaksioneve", "bank_transactions"],
    ["bank_unreconciled", "Pajtimi", "Transaksionet e papajtuara", "bank_reconciliation"],
    ["bank_reconciled_register", "Pajtimi", "Regjistri i pajtimit", "bank_transactions"],
    ["bank_transfer_status", "Transferta", "Statusi i transfertave", "bank_transfers"],
    ["bank_transfer_register", "Transferta", "Regjistri i transfertave", "bank_transfers"],
    ["bank_cash_flow", "Analizë", "Fluksi i parasë", "bank_transactions"],
    ["bank_incoming_summary", "Analizë", "Përmbledhja e hyrjeve", "bank_transactions"],
    ["bank_outgoing_summary", "Analizë", "Përmbledhja e daljeve", "bank_transactions"],
    ["bank_reconciliation_summary", "Pajtimi", "Përmbledhja e pajtimit", "bank_reconciliation"],
  ]),
];

export const REPORT_BASE_KEYS: Record<string, string> = Object.fromEntries(REPORT_CATALOG.map(item => [item.key, item.baseKey ?? item.key]));

export const REPORTS_BY_MODULE: Record<ReportModule, ReportCatalogItem[]> = {
  Blerje: REPORT_CATALOG.filter(item => item.module === "Blerje"),
  Shitje: REPORT_CATALOG.filter(item => item.module === "Shitje"),
  Magazina: REPORT_CATALOG.filter(item => item.module === "Magazina"),
  Kontabilitet: REPORT_CATALOG.filter(item => item.module === "Kontabilitet"),
  CRM: REPORT_CATALOG.filter(item => item.module === "CRM"),
  Banka: REPORT_CATALOG.filter(item => item.module === "Banka"),
};
