import { mkdirSync, writeFileSync } from "node:fs";
mkdirSync("docs", { recursive: true });
const docs = {
  "MODULES.md": "# Module të repository-t\n\n| Modul | Source kryesor | Përshkrim |\n|---|---|---|\n| Klientë/CRM | client/src/pages dhe customer procedures | Partnerë, kërkim dhe lidhje me dokumente |\n| Shitje | client/src/pages/SalesInvoices.tsx dhe server/sales.ts | Fatura, oferta, porosi, dërgesa, kthime, pagesa, import/export dhe raporte |\n| Blerje | client/src/pages/Purchases.tsx dhe server/purchase.ts | Fatura dhe regjistër blerjesh |\n| Magazina/Stok | client/src/pages/Inventory.tsx dhe server/inventory.ts | Artikuj, njësi, magazina, hyrje/dalje dhe stok |\n| Arka/Banka | server/crmBanking.ts | Likuiditete dhe pagesa |\n| Kontabilitet | server/accounting.ts | Workspace dhe llogari kontabël |\n| Raporte | shared/reportCatalog.ts dhe pages report | Filtra, PDF, Excel dhe lidhje burimi |\n| Konfigurime | client/src/pages dhe components | Parametra, kompani dhe katalogë |\n| Auth/RBAC | server/_core dhe server/companyRoles.ts | Sesione, role dhe multi-company |\n\nModuli Pagat nuk është pjesë e eksportit BioBes sipas kufizimit të projektit.\n",
  "ADD-MODULE.md": "# Shtimi i një moduli\n\nPërcakto entitetet dhe company scope në schema, krijo migration SQL, shto helper-at në server/db.ts, procedurat tRPC me Zod, page/components në client/src, menu/link dhe permission. Shto formularin, validimet, raportin dhe teste Vitest. Ekzekuto pnpm check, pnpm test dhe pnpm build. Çdo mutation duhet të verifikojë companyId.\n",
  "ADD-REPORT.md": "# Shtimi i një raporti\n\nRegjistro raportin në shared/reportCatalog.ts, ndërto query-n me companyId dhe filtrat në router, krijo view në client/src/pages ose komponentin e modulit dhe përdor eksportuesit ekzistues PDF/Excel. Ruaj të njëjtat kolona në web dhe dokument, testo filtrat e kombinuar, totalet dhe rastin bosh. Për linke burimi përdor SourceDocumentLink.\n",
  "ADD-FORM.md": "# Shtimi ose ndryshimi i formularit\n\nPërcakto input schema me Zod, required fields, default-et dhe validimin business. Në React përdor controlled selects për të dhënat asinkrone, requestSubmit për toolbar dhe tRPC mutation për ruajtje. Kontrollo artikuj realë, sasi pozitive, magazinë dhe company scope. Shto test regresioni dhe verifiko desktop/mobile.\n",
  "API.md": "# API\n\nAPI përdor tRPC nën /api/trpc. Kontratat e plota janë në server/routers.ts dhe router files. Procedurat autentike përdorin session context; procedurat administrative kontrollojnë role. Modulet kryesore kanë list/get/create/update/delete ose transition procedures për customer, product, warehouse, purchase, salesInvoice, salesQuotation, salesOrder, delivery, salesReturn, report, banking dhe accounting. Lexo router-in si burim autoritar për input-et dhe gabimet Zod.\n",
  "DEPLOY-CLOUD.md": "# Deploy cloud\n\nPërdor MySQL/TiDB me SSL, secret manager për variables, domain HTTPS dhe backup të testuar. Build: pnpm install --frozen-lockfile && pnpm build; start: pnpm start. Konfiguro OAuth callback, DATABASE_URL dhe JWT_SECRET vetëm në secrets. Ruaj company scope në çdo query dhe monitoro logs, rate limits dhe migrimet.\n",
  "BUILD-WINDOWS.md": "# Build Windows\n\nWrapper-i është te desktop/ dhe përdor Electron me context isolation. Në Windows ekzekuto cd desktop, pnpm install dhe pnpm start. Për installer ekzekuto pnpm build:windows; output-i del te desktop/release/. Target-i mund të jetë BIOBES_URL ose server lokal http://localhost:3000. Offline i plotë kërkon database/server lokal.\n"
};
for (const [name, content] of Object.entries(docs)) writeFileSync(`docs/${name}`, content);
writeFileSync("CONTRIBUTING.md", "# Contributing\n\nPërdor branch develop për punë të reja dhe main për release. Commit-et përdorin Conventional Commits si feat, fix, docs dhe chore. Çdo pull request shpjegon company scope, migration impact, testet dhe ndikimin te raportet. Ekzekuto pnpm check && pnpm test && pnpm build para review. Mos commit-o secrets, të dhëna reale, build artifacts ose modulin Pagat.\n");
writeFileSync("docs/README.md", "# Dokumentacioni\n\nLexo INSTALL, ARCHITECTURE, MODULES, ADD-MODULE, ADD-REPORT, ADD-FORM, API, DEPLOY-CLOUD dhe BUILD-WINDOWS sipas nevojës.\n");
